name: runs every 9:00(JST)

on:
  schedule:
    - cron:  "00 24 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: install requirements.txt
      run: pip3 install -r requirements.txt

    - name: save json
      run: python3 get_before_prefectures_data.py

    - name: deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./data
        publish_branch: 9
